// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcMF3nWC1ZuqsmytUF-O-i6BTOzECAq0',
    appId: '1:684144505252:web:3bddd53fbfd4104c981131',
    messagingSenderId: '684144505252',
    projectId: 'getthings-7925e',
    authDomain: 'getthings-7925e.firebaseapp.com',
    storageBucket: 'getthings-7925e.firebasestorage.app',
    measurementId: 'G-DZT0LYC9XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hnEYpToZfR4Re06w4miABDq3n3xVaFY',
    appId: '1:684144505252:android:4bd4d37390b26a9d981131',
    messagingSenderId: '684144505252',
    projectId: 'getthings-7925e',
    storageBucket: 'getthings-7925e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6HEc05YObwrwOEyNO_REBlwC7MUJjj0o',
    appId: '1:684144505252:ios:9ccf34a6e6d2112b981131',
    messagingSenderId: '684144505252',
    projectId: 'getthings-7925e',
    storageBucket: 'getthings-7925e.firebasestorage.app',
    iosBundleId: 'com.codesol.getThings',
  );
}
